### ISSUE TITLE
How to send HTML emails?

### ISSUE THREAD

**Issue by Spoowy** [choptastic/sparkler#1]
Thanks for this cool package!
I'm wondering how one would send not only text-only emails but also HTML-code.

My HTML code is displayed as text, unfortunately.

Cheers,
Erwin

**Comment by choptastic** [comment]
Hi Erwin!

Thanks for the kind words!

Currently, sparkler only supports text emails (as that's really all I use).

However, it could be pretty easily modified to add HTML body from the sparkpost documentation:

https://developers.sparkpost.com/api/transmissions.html

As you can see in the code, I'm only specify in the `text` attribute ([here](https://github.com/choptastic/sparkler/blob/master/src/sparkler.erl#L148)), however, modifying sparkler to add HTML support should be reasonably straightforward, and I'm 100% open to a pull request if you're feeling so inclined.

We'd need a few changes:

1) Rename the 'data' field in the record to 'text' and add a new 'html' field to the record https://github.com/choptastic/sparkler/blob/master/src/sparkler.erl#L28

2) Add a new `send_html/4` and `send_html/5` functions, which instead of specifying the `text` attribute instead specify the `html` attribute. https://github.com/choptastic/sparkler/blob/master/src/sparkler.erl#L37-L48

3) Then make sure when sending, that the appropriate field is specified in the actual API call to sparkpost  https://github.com/choptastic/sparkler/blob/master/src/sparkler.erl#L148

Is this something you feel inclined to tackle?  I'd be happy to merge in those changes if you do.

**Comment by Spoowy** [comment]
I will tackle it this week, as I am more familiar with the language now.

**Comment by choptastic** [comment]
Awesome! Looking forward to it!

Thanks!

-Jesse

**Comment by Spoowy** [comment]
Hey Jesse!

I've managed to make the changes: https://github.com/choptastic/sparkler/pull/2
Let me know what you think! By the way, I really respect you for your clean code.

Cheers,
Erwin

**Comment by choptastic** [comment]
Thanks so much for the contribution, and I very much appreciate the appreciation for my code.

I'll likely be adding some helper functions `send_text` and `send_html` with `send` being the core of both.

Either way, thanks for submitting the pull request!
